variable "aws_region" {}
variable "instance_type" {}
variable "key_name" {}
variable "project_name" {}
variable "albname" {}
variable "nlbname" {}
variable "albtgname" {}
variable "nlbtgname" {}
variable "alb_certificate_arn" {}
variable "domainname" {}
variable "environment" {}
